package com.example.walactv.network.dto

import com.google.gson.annotations.SerializedName

data class CatalogPageResponse(
    val items: List<CatalogItemDto> = emptyList(),
    val total: Int = 0,
    val page: Int = 1,
    @SerializedName("page_size") val pageSize: Int = 24,
    val pages: Int = 0,
    @SerializedName("has_next") val hasNext: Boolean = false,
    @SerializedName("has_prev") val hasPrev: Boolean = false,
)

data class CatalogItemDto(
    val id: Any? = null,
    @SerializedName("episode_id") val episodeId: Any? = null,
    @SerializedName("channel_id") val channelId: Any? = null,
    @SerializedName("provider_id") val providerId: Any? = null,
    val nombre: String? = null,
    val title: String? = null,
    val name: String? = null,
    @SerializedName("display_name") val displayName: String? = null,
    @SerializedName("channel_name") val channelName: String? = null,
    val type: String? = null,
    @SerializedName("content_type") val contentType: String? = null,
    @SerializedName("media_type") val mediaType: String? = null,
    val group: String? = null,
    @SerializedName("grupo") val grupo: String? = null,
    val description: String? = null,
    @SerializedName("overview") val overview: String? = null,
    @SerializedName("overview_en") val overviewEn: String? = null,
    val logo: String? = null,
    @SerializedName("logo_url") val logoUrl: String? = null,
    val image: String? = null,
    @SerializedName("image_url") val imageUrl: String? = null,
    val poster: String? = null,
    @SerializedName("poster_url") val posterUrl: String? = null,
    val backdrop: String? = null,
    @SerializedName("backdrop_url") val backdropUrl: String? = null,
    @SerializedName("tmdb_poster_path") val tmdbPosterPath: String? = null,
    @SerializedName("tmdb_backdrop_path") val tmdbBackdropPath: String? = null,
    @SerializedName("tmdb_id") val tmdbId: Any? = null,
    @SerializedName("tmdb_title") val tmdbTitle: String? = null,
    @SerializedName("tmdb_name") val tmdbName: String? = null,
    @SerializedName("vote_average") val voteAverage: Double? = null,
    val rating: Double? = null,
    val year: Int? = null,
    @SerializedName("release_date") val releaseDate: String? = null,
    val genres: List<String>? = null,
    @SerializedName("runtime_minutes") val runtimeMinutes: Int? = null,
    @SerializedName("total_seasons") val totalSeasons: Int? = null,
    @SerializedName("season_number") val seasonNumber: Int? = null,
    @SerializedName("episode_number") val episodeNumber: Int? = null,
    @SerializedName("serie_name") val serieName: String? = null,
    @SerializedName("stream_options") val streams: List<StreamDto>? = null,
    @SerializedName("stream_url") val streamUrl: String? = null,
    val country: String? = null,
    @SerializedName("channel_number") val channelNumber: Int? = null,
    val badge: String? = null,
    @SerializedName("badge_text") val badgeText: String? = null,
    val subtitle: String? = null,
    val url: String? = null,
    @SerializedName("event_competition") val eventCompetition: String? = null,
    @SerializedName("event_home_team") val eventHomeTeam: String? = null,
    @SerializedName("event_away_team") val eventAwayTeam: String? = null,
    @SerializedName("event_time") val eventTime: String? = null,
)

data class StreamDto(
    val url: String? = null,
    val label: String? = null,
    val country: String? = null,
    val quality: String? = null,
    @SerializedName("provider_id") val providerId: String? = null,
    val headers: Map<String, String>? = null,
)
